# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tictoc', ['core', 'network'])
    module.source = [
	'model/tictoc-net-device.cc',
	'model/tictoc-channel.cc',
        'helper/tictoc-helper.cc'
        ]

    module_test = bld.create_ns3_module_test_library('tictoc')
    module_test.source = [
        'test/tictoc-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'tictoc'
    headers.source = [
	'model/tictoc-net-device.h',
	'model/tictoc-channel.h',
        'helper/tictoc-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

